config/routes.rb
Rails.application.routes.draw do
  resources :resources
  resources :service_providers
  get 'user/index'
  devise_for :users
  get 'dashboard/index'
  root 'static_pages#home'
  get 'rules',      to: 'static_pages#rules'
  get 'hhms',       to: 'static_pages#hhms'
  get 'providers',  to: 'static_pages#providers'
  get 'contact',    to: 'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :user
end

app/models/service_provider.rb
class ServiceProvider < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include Gravtastic
  gravtastic

  has_many :service_providers
  has_many :resources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:link, :name, :description, :user_id)
    end
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: [:show, :edit, :update, :destroy]

  # GET /service_providers
  # GET /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1
  # GET /service_providers/1.json
  def show
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers
  # POST /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully created.' }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1
  # PATCH/PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1
  # DELETE /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: 'Service provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_provider_params
      params.require(:service_provider).permit(:name, :address, :telephone, :email, :acc_number, :active, :user_id,
                                               :link)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # users are redirected to the dashboard upon login.
    if current_user
      redirect_to dashboard_index_path
    end
  end

  def rules
  end

  def hhms
  end

  def providers
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def gravatar

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Herga Intranet"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to Herga Dashboard</h1>


<p>As a registered user, your dashboard acts like a gateway to all the tools used at Herga Home.</p>
<br/>
<p>At the top of every page, you will have the "Tools" tab displayed throughout the site, to help you navigate easily.</p>
<br/>
<p>Under the Tools tab, there are sub-tabs with links to the various tools.</p>
<br/>
<p>Please note that for some tools you may be required to enter your username and password to access the system(s).</p>
<br/>
<p>The Username and password may be different than the one used to access this site.</p>
<br/>
<p>For security reasons, please do not share your password with anyone. </p>
<br/>
<p>If you experience any difficulties navigating through the site, Please contact the systems administrator</p>

<br/>

<p>Thanks in advance for your cooperation.</p>
<br/>
<p> Site Admin Team. </p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Home Intranet</a>
    by <a href="https://ie.linkedin.com/in/bernardokava">Bernardo Kava</a>
  </small>
  <nav>
    <ul>

      <li><%= link_to "Rules", rules_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Learn enough</a></li>
      <% if current_user %>
        <li><%= link_to "HHMS",   hhms_path %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Herga Intranet", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Rules", rules_path %></li>

        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Tools <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "HHMS",  hhms_path %></li>
              <li><%= link_to "Service Providers",  service_providers_path %></li>
              <li><%= link_to "Resources",  resources_path %></li>
            </ul>
        <% end %>

        <% if current_user  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>


      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% if current_user %>
    <%= render 'user/gravatar'%>
  <% else %>
    <%= render 'user/visitorNotice'%>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/resources/_form.html.erb
<% provide(:title, "Resources") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.label :name %>
    <%= form.text_field :name , class: 'form-control'%>



    <%= form.label :description %>
    <%= form.text_area :description , class: 'form-control'%>



    <%= form.hidden_field :user_id ,value: current_user.id %>



    <%= form.label :link %>
    <%= form.text_area :link, class: 'form-control' %>


      <br/>

    <p><%= form.submit %></p>

<% end %>
  </div>
</div>

app/views/resources/edit.html.erb
<% provide(:title, " Edit Resources") %>
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<% provide(:title, " Resources") %>
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<div class="table-wrapper">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.description %></td>
        <td><%= resource.user.email %></td>
        <td><%= link_to 'Show', resource %></td>

        <% if current_user.admin == true %>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<% provide(:title, " New Resource") %>
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<% provide(:title, " Resources") %>
<p id="notice"><%= notice %></p>

<h1>Resource:</h1>
<h2>Click on the name of the resource to access it.</h2>
<hr/>
<p>
  <strong>Name:</strong>
  <%= link_to @resource.name, @resource.link %>
</p>
<hr/>
<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>
<hr/>
<p>
  <strong>User:</strong>
  <%= @resource.user_id %>
</p>
<hr/>
<hr/>
<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/service_providers/_form.html.erb
<% provide(:title, "Service Providers") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_with(model: service_provider, local: true) do |form| %>
  <% if service_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_provider.errors.count, "error") %> prohibited this service_provider from being saved:</h2>

      <ul>
      <% service_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>


    <%= form.label :address %>
    <%= form.text_area :address, class: 'form-control' %>


    <%= form.label :telephone %>
    <%= form.text_field :telephone, class: 'form-control' %>



    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>


    <%= form.label :acc_number %>
    <%= form.text_field :acc_number , class: 'form-control'%>


    <%= form.label :active %>
    <%= form.check_box :active %>



    <%= form.label :link %>
    <%= form.text_area :link, class: 'form-control'%>




    <%= form.hidden_field :user_id ,value: current_user.id, :disabled => false, class: 'form-control'%>

<br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  </div>
</div>

app/views/service_providers/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Editing Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<% provide(:title, "Service Providers") %>
<p id="notice"><%= notice %></p>

<h1>Service Providers</h1>

<div class="table-wrapper">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Acc number</th>
      <th>Active</th>
      <th>User Email</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= service_provider.name %></td>
        <td><%= service_provider.address %></td>
        <td><%= service_provider.telephone %></td>
        <td><%= service_provider.email %></td>
        <td><%= service_provider.acc_number %></td>
        <td><%= service_provider.active %></td>
        <td><%= service_provider.user_id %></td>
        <td><%= service_provider.user.email %></td>
        <td><%= link_to 'Show', service_provider %></td>

        <% if current_user.admin == true %>
          <td><%= link_to 'Edit', edit_service_provider_path(service_provider) %></td>
          <td><%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Service Provider', new_service_provider_path %>

app/views/service_providers/new.html.erb
<% provide(:title, "New Provider") %>
<h1>New Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Back', service_providers_path %>

app/views/service_providers/show.html.erb
<% provide(:title, "View Provider") %>
<p id="notice"><%= notice %></p>


<h1>Service Provider:</h1>
<h2>Click on the name of the service provider to access it.</h2>
<hr/>
<p>
  <strong>Name:</strong>

  <%= link_to @service_provider.name , @service_provider.link%>

</p>
<hr/>
<p>
  <strong>Address:</strong>
  <%= @service_provider.address %>
</p>
<hr/>
<p>
  <strong>Telephone:</strong>
  <%= @service_provider.telephone %>
</p>
<hr/>
<p>
  <strong>Email:</strong>
  <%= @service_provider.email %>
</p>
<hr/>
<p>
  <strong>Acc number:</strong>
  <%= @service_provider.acc_number %>
</p>
<hr/>
<p>
  <strong>Active:</strong>
  <%= @service_provider.active %>
</p>
<hr/>
<p>
  <strong>User:</strong>
  <%= @service_provider.user_id %>
</p>

<hr/>
<hr/>
<% if current_user.admin == true %>
<%= link_to 'Edit', edit_service_provider_path(@service_provider) %> |
<% end %>
<%= link_to 'Back', service_providers_path %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="center jumbotron">

  <h2>
    For all technical issues?  Contact me!
  </h2>

  <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %>

</div>

app/views/static_pages/hhms.html.erb
<% provide(:title, "HHMS") %>

<h1>HHMS</h1>
<p>
Herga Home Management System (HHMS) is a moodle based web application.
  <a href="http://10.1.10.9/"><em>HHMS </em>  </a> contains a variety of records, including HBR.
  It is essentially the main system of record pending the further expansion of this intranet site.
</p>

<br>
<hr/>
<div class= "center jumbotron">
<%= link_to image_tag("moodle.png", alt: "moodle logo",:size => "200x100" ),
            'http://10.1.10.9/' %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h2>Welcome to the house intranet page.</h2>

  <h2>
feel free to register with an
    email address and password.  it is all internal therefore no email verifications will be sent.
  </h2>

  <%= link_to "Register!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/providers.html.erb
<% provide(:title, "Providers") %>


<h1>Service Providers</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help
    section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
    Tutorial</em> book</a>.
</p>

app/views/static_pages/rules.html.erb
<% provide(:title, "Rules") %>

<h1>House Rules</h1>
<p>
  The following rules apply to anyone logged onto the Herga.
  net network or anyone using Home computing equipment:
</p>

<ol>
  <li>Under no circumstances shall any hardware equipment be unplugged or moved without approval of
    the system administrator. </li>
  <li>Under no circumstances shall computer settings of any computers in the
    house be changed by users. </li>
  <li>All mobile phones connected to Herga.net Wireless access points are given IP addresses by the Herga.net
    DHCP Servers. </li>
  <li>Access to wireless network can be revoked on devices that violate the network policy. </li>
  <li>As of 21/01/2018, all persons under the age of 18 shall be in bed by 10.30 PM.</li>
  <li>All person under the age of 18 must eat fruit and vegetables if the produce is made available. </li>
  <li>The house must be maintained clean at all times. All persons must adopt a Clean AS You Go approach. </li>
  <li>All person under the age of 18 must eat fruit and vegetables if the produce is made available. </li>
  <li>The administration office is not a playroom. Only authorized persons may enter this room. </li>
  <li>Writing on the walls is not permitted under any circumstances. </li>
  <li>Anyone who deviates from the rule will face sanctions. The nature of those sanctions is decided by
    the sanctioned as he/ she sees fit. </li>




</ol>

app/views/user/_gravatar.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= image_tag current_user.gravatar_url %>
        <%= current_user.email %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </h1>
    </section>
  </aside>
</div>

app/views/user/_visitorNotice.html.erb
<div class = visitorNotice>

  <p>you are currently browsing as a visitor.</p>
  <p>Please login to access Herga Tools</p>


</div>